<?php
/**
 * Created by JetBrains PhpStorm.
 * User: nhan
 * Date: 1/15/15
 * Time: 7:53 AM
 * To change this template use File | Settings | File Templates.
 */

function merc_global_menu()
{
    $items['admin/portal/dashboard'] = array(
        'title' => 'Admin Dashboard',
        'page callback' => 'merc_global_admin_dashboard',
        'access arguments' => array('admin dashboard'),
        'type' => MENU_LOCAL_ACTION,
        'weight' => 1,
    );


    return $items;
}

function merc_global_permission() {
    return array(
        'admin dashboard' => array(
            'title' => t('Administer dashboard'),
            'description' => t('Perform administration tasks for my module.'),
        ),
    );
}



/*
 * Implement hook_theme
 */

function merc_global_theme() {
    return array(
        'merc_global_panel' => array(
            'render element' => 'element',
            'template' => 'theme/merc-global-panel',
        ),

    );
}

function merc_global_admin_dashboard(){
    global $user;
    drupal_add_css(drupal_get_path('module','merc_global').'/admin_panel/admin-panel.css');
    return array('#theme' => 'merc_global_panel');
}


